export const CATEGORIES = {
  all: {
    id: 'all',
    label: 'All',
    labelPT: 'Todos',
    primary: '#1F1B1D',
    secondary: '#E0DDD8',
    cardBg: '#FFFFFF',
    radius: '1px',
    font: "'Archiv Grotesk', sans-serif",
    headlineWeight: 700,
    headlineTransform: 'none',
    headlineTracking: '-0.3px',
  },
  sports: {
    id: 'sports',
    label: 'Sports',
    labelPT: 'Esportes',
    primary: '#1AA275',
    secondary: '#9BE7CF',
    cardBg: '#FFFFFF',
    radius: '20px',
    font: "'Barlow Condensed', sans-serif",
    headlineWeight: 800,
    headlineTransform: 'uppercase',
    headlineTracking: '-0.3px',
  },
  politics: {
    id: 'politics',
    label: 'Politics',
    labelPT: 'Política',
    primary: '#292536',
    secondary: '#B4AEC0',
    cardBg: '#FFFFFF',
    radius: '2px',
    font: "'Playfair Display', serif",
    headlineWeight: 700,
    headlineTransform: 'none',
    headlineTracking: '0',
  },
  news: {
    id: 'news',
    label: 'News',
    labelPT: 'Atualidades',
    primary: '#167BFF',
    secondary: '#98C3FD',
    cardBg: '#FFFFFF',
    radius: '12px',
    font: "'Lora', serif",
    headlineWeight: 600,
    headlineTransform: 'none',
    headlineTracking: '0',
  },
  tech: {
    id: 'tech',
    label: 'Technology',
    labelPT: 'Tecnologia',
    primary: '#8F3AF6',
    secondary: '#CEA7FF',
    cardBg: '#FFFFFF',
    radius: '8px',
    font: "'Space Mono', monospace",
    headlineWeight: 700,
    headlineTransform: 'none',
    headlineTracking: '-0.5px',
  },
  business: {
    id: 'business',
    label: 'Business',
    labelPT: 'Negócios',
    primary: '#120199',
    secondary: '#BCB5F4',
    cardBg: '#FFFFFF',
    radius: '4px',
    font: "'DM Serif Display', serif",
    headlineWeight: 400,
    headlineTransform: 'none',
    headlineTracking: '0',
  },
}

export const PORTALS = {
  g1: {
    id: 'g1',
    name: 'G1',
    feeds: {
      all:      'https://g1.globo.com/rss/g1/',
      sports:   'https://ge.globo.com/rss/ge/',
      politics: 'https://g1.globo.com/rss/g1/politica/',
      tech:     'https://g1.globo.com/rss/g1/tecnologia/',
      business: 'https://g1.globo.com/rss/g1/economia/',
      news:     'https://g1.globo.com/rss/g1/',
    },
  },
  folha: {
    id: 'folha',
    name: 'Folha',
    feeds: {
      all:      'https://feeds.folha.uol.com.br/folha/rss091.xml',
      sports:   'https://feeds.folha.uol.com.br/esporte/rss091.xml',
      politics: 'https://feeds.folha.uol.com.br/poder/rss091.xml',
      tech:     'https://feeds.folha.uol.com.br/tec/rss091.xml',
      business: 'https://feeds.folha.uol.com.br/mercado/rss091.xml',
      news:     'https://feeds.folha.uol.com.br/folha/rss091.xml',
    },
  },
  uol: {
    id: 'uol',
    name: 'UOL',
    feeds: {
      all:      'https://rss.uol.com.br/feed/noticias.xml',
      sports:   'https://rss.uol.com.br/feed/esportes.xml',
      politics: 'https://rss.uol.com.br/feed/politica.xml',
      tech:     'https://rss.uol.com.br/feed/tecnologia.xml',
      business: 'https://rss.uol.com.br/feed/economia.xml',
      news:     'https://rss.uol.com.br/feed/noticias.xml',
    },
  },
  espn: {
    id: 'espn',
    name: 'ESPN',
    feeds: {
      all:      'https://www.espn.com.br/rss/feed/',
      sports:   'https://www.espn.com.br/rss/feed/',
      politics: null,
      tech:     null,
      business: null,
      news:     null,
    },
  },
  techcrunch: {
    id: 'techcrunch',
    name: 'TechCrunch',
    feeds: {
      all:      'https://techcrunch.com/feed/',
      sports:   null,
      politics: null,
      tech:     'https://techcrunch.com/feed/',
      business: 'https://techcrunch.com/feed/',
      news:     'https://techcrunch.com/feed/',
    },
  },
  cnn: {
    id: 'cnn',
    name: 'CNN Brasil',
    feeds: {
      all:      'https://www.cnnbrasil.com.br/feed/',
      sports:   'https://www.cnnbrasil.com.br/esportes/feed/',
      politics: 'https://www.cnnbrasil.com.br/politica/feed/',
      tech:     'https://www.cnnbrasil.com.br/tecnologia/feed/',
      business: 'https://www.cnnbrasil.com.br/economia/feed/',
      news:     'https://www.cnnbrasil.com.br/feed/',
    },
  },
}
